# fly.toml app configuration file generated for jazmeen-server-1 on 2025-02-09T17:09:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jazmeen-ecqcuq"
primary_region = "lhr"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[mounts]]
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"
auto_extend_size_threshold = 80
destination = "/data"
source = "data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"